### ISSUE TITLE
Feature idea: ASCII marbles diff 

### ISSUE THREAD

**Issue by vladinator1000** [just-jeb/jest-marbles#330]
Hi y'all, I've been loving using jest-marbles lately 💅, but reading frame diffs as json is a bit hard to read when a test fails. Here's an idea.
What if we printed an ASCII diff in addition to the JSON?

**Expected**
a|

**Received**
ab|

**Diff** 
ab|
(imagine the "b" colored in red and the rest green)

**Where**
_a_: is some JSON
_b_: is some other JSON

**Comment by just-jeb** [comment]
Hey @vladinator1000! Actually it does work this way (and if it doesn't then it's a bug). However it works like this only for constants, not for objects. If `a` and `b` are numbers/characters then they are marblizable, and we can translate them to strings.  
If one of them is an object then it's a problem, since when you get something else (not the expected object) you can't translate it into a single character.  
For instance, if you expect `a: {hello: 'hi', hi: 'hello'}` but instead you get `{hello: 'world'}`, you can't really translate `{hello: 'world'}` to anything. It's not `a`, not `b` - it's something that is undefined in the user's world.
